# Generated by Django 6.0.2 on 2026-03-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="static/images.jpeg", null=True, upload_to=""
            ),
        ),
    ]
