# Generated by Django 6.0.2 on 2026-03-08 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_topic_rooms_host_message_rooms_topic"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rooms",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.AddField(
            model_name="rooms",
            name="participant",
            field=models.ManyToManyField(
                blank=True, related_name="Participants", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
