# Generated by Django 6.0.2 on 2026-03-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="static/images/images.jpeg", null=True, upload_to=""
            ),
        ),
    ]
