# Generated by Django 6.0.2 on 2026-03-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="avatars/images.jpeg", null=True, upload_to=""
            ),
        ),
    ]
